### ISSUE TITLE
Just my notes

### ISSUE THREAD

**Issue by HelgeKrueger** [steve-bate/activitypub-mincore#1]
1. "id (MUST be valid for dereferencing)" ---> I'm not sure what this means. If this means what I think it means. I would prefer "MUST agree with the URL."
2. I would prefer if it was clearly stated that inbox is a POST endpoint. A similar URI = URL sentence is appropriate.
3. "Must support inbox Follow activity processing" -> There is no such thing. What there is processing for sending an Accept to a Follow activity and receiving one. Similarly for Undo.
4. " ActivityPub Minimal Core " -> A better name would include 'federation API', I know it's all people use from AP but it pays to be precise.
5.

**Comment by steve-bate** [comment]
> 1. "id (MUST be valid for dereferencing)" ---> I'm not sure what this means. If this means what I think it means. I would prefer "MUST agree with the URL."

It means you can't use an arbitrary ID, like a URN, that can't be dereferenced. Maybe the requirement is *too* obvious and doesn't need to be stated. I'll take another look.

> 2. I would prefer if it was clearly stated that inbox is a POST endpoint. A similar URI = URL sentence is appropriate.

I'll update the text. It MUST be a POST endpoint, it MAY be a GET endpoint too.

> 3. "Must support inbox Follow activity processing" -> There is no such thing. What there is processing for sending an Accept to a Follow activity and receiving one. Similarly for Undo.

I'm not understanding your point here. Requiring Undo support makes sense to me, but I don't think that's your point.

> 4. " ActivityPub Minimal Core " -> A better name would include 'federation API', I know it's all people use from AP but it pays to be precise.

I used the name in the context of discussion around AP Minimal Core + Domain-specific Interop/Compliance profiles. It's not really a complete federation API for most domains (in the absence of an interop profile) but I agree the core effectively strips out C2S.

**Comment by HelgeKrueger** [comment]
I'll open a new issue for the Follow stuff. It will take some time as I should probably make sure I can express myself clearly.

Feel free to close this issue if you consider the other stuff completed.

**Comment by steve-bate** [comment]
Sounds good. Thanks for your comments. I've made some related README updates and look forward to the Follow-related information.
