### ISSUE TITLE
'minimal core' implies this is a subset of the requirements of AP/AS2 but it actually is a superset

### ISSUE THREAD

**Issue by gobengo** [steve-bate/activitypub-mincore#8]
'minimal core' implies this is a subset of the requirements of AP/AS2 but it actually is a superset

This isn't a core, it's the opposite. It introduces *more* requirements.

e.g. extensions aside, this is a valid AS2 document or AP object:
```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": ["Activity", "Object"],
  "summary": "Sally did something to a note",
  "actor": {
    "type": "Person",
    "name": "Sally"
  },
  "object": {
    "type": "Note",
    "name": "A Note"
  }
}
```

but because activitypub-mincore extends the requirement set to add a new requirement that `type` cannot be an array, it makes it invalid in activitypub-mincore.

I think it is misleading to represent this as minimal or and especially an 'activitypub core'. Just give it a new name like 'monomorphism' and say it's 'activitypub inspired' :P

**Comment by steve-bate** [comment]
"Minimal" in this context is minimal/core *behavior*, not minimal requirements. In a sense, the current spec has relatively minimal requirements. This experiment is exploring an alternative to that (arguably, excessive and frequently unneeded) flexibility.

I'll consider adding some information to the README.md to make this more clear.

> add a new requirement that type cannot be an array

Or...  it *removes* the current requirement to support `type` arrays. The current requirement allows a single `type` URI (compacted form of a single-element `type` array) or array with multiple `type` values. The Minimal Core considers only a subset of those variations of `type` specification as valid (single string/URI).

As the experiment evolves this will probably extend to other properties as well. For example, `actor`, is non-functional but multiple actors are not used in any AP server I know about. Still, a server must (or should) be prepared to process an array of actors. Few do, and just throw exceptions or crash.

> e.g. extensions aside, this is a valid AS2 document 

True, but...
```json
{}
```
is also a valid AS2 document. It wouldn't be considered valid in AP Min Core and I'm ok with that. ;-)  I'm very surprised by what *is* valid in ActivityStreams2 (based on looking at the W3C AS2 test documents).

**Comment by bumblefudge** [comment]
sorry to jump in without much context but isn't multiple types a hard requirement of the JSON-LD syntax that is needed for extensions that require their own namespaces? I thought the whole idea of FEPs was that they propose additional @context files so that nonsupporting implementations can ignore additional types it doesn't understand from the type array?

**Comment by steve-bate** [comment]
> sorry to jump in without much context but isn't multiple types a hard requirement of the JSON-LD syntax that is needed for extensions that require their own namespaces? I thought the whole idea of FEPs was that they propose additional @context files so that nonsupporting implementations can ignore additional types it doesn't understand from the type array?

Context is very important for this discussion. 

As described in the README.md, AP Min Core is not intended to be used alone (although it can be in limited ways). The idea is that this is the foundation for creating interop specifications for specific social domains or cross-cutting functionality. Those documents haven't been written yet. Those interop specs may support extensibility or may not. If they do, maybe they'll consider a different approach than JSON-LD. Something like JSON Schema, for example.

AP Min Core doesn't use JSON-LD. It supports the JSON perspective allowed by AP/AS2 and used by most implementations. It doesn't mean that JSON-LD compatible messages can't be used (with restrictions), just that there's no expectation to expand it, compact it, or treat it as the RDF serialization that it is. There's is no extensibility technique defined in AP Min Core. Those options will be something for higher-level documents to define.

This experiment is also not related to FEPs at the moment.

**Comment by steve-bate** [comment]
> isn't multiple types a hard requirement of the JSON-LD syntax that is needed for extensions

Although it's a little off-topic for this project, that doesn't seem to be the case (a hard requirement) although the AS2 primer describes it as a best practice.

W3C AS2 Test Document: `vocabulary-extype-jsonld.json`:
```json
{
  "@context": "http://www.w3.org/ns/activitystreams",
  "name": "A foo",
  "type": "http://example.org/Foo"
}
```
This is an extension without multiple types.

Interestingly (to me), I *think* this is also a valid AS2 message (I need to confirm it):
```json
{
  "@context": ""https://schema.org",
  "@type": "schema:Thing"
  "schema:name": "A thing",
}
```
Even though the AS2 spec requires the AS2 context to be implicitly added, it's not used in this case. This is really a tangent, but I'm including it because I think this highlights how AS2 may be *too* flexible for effective interoperability. However, a constrained subset of AS2 could be *very* valuable for specific use cases.
